version: "3"
services:
  postgres:
    image: "postgres:12-alpine"
    container_name: "book-postgres"
    environment: 
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/postgresql/data"